name: Publish Plugin to PyPI

on:
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build and Publish
        run: |
          cd web
          npm install
          npm run build
          poetry build
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.TEST_PYPI_PASSWORD }}
